Update config

diff --git a/.local/bin/bootstrap b/.local/bin/bootstrap
--- a/.local/bin/bootstrap
+++ b/.local/bin/bootstrap
@@ -117,8 +117,6 @@ if [[ "$(yadm config --get-all local.class)" == *"work"* && "$(yadm config --get
     curl -d "Work setup complete" https://ntfy.conway.dev/notifications -H "Authorization: Bearer ${NTFY_TOKEN}"
 fi
 
-clone-all
-
 install-all || echo "Installing some programs failed"
 
 if command -v fc-cache > /dev/null; then
@@ -153,6 +151,59 @@ if command -v ansible /dev/null && [[ -e ~/Git/ansible/main.yml ]]; then
     cd
 fi
 
+clone-all
+
 echo "All done!"
 
 curl -d "Bootstrapping complete on $(uname -n)" https://ntfy.conway.dev/notifications -H "Authorization: Bearer ${NTFY_TOKEN}" &> /dev/null
+
+# if [[ "$(yadm config --get-all local.class)" == *"server"* ]]; then
+#     curl -fsSL https://get.docker.com -o ~/.local/bin/get-docker
+#     chmod +x ~/.local/bin/get-docker
+#     sh ~/.local/bin/get-docker
+#     sudo groupadd docker || echo "Group already exists"
+#     sudo usermod -aG docker $USER
+#     newgrp docker
+# else
+#     if [[ ! -e ~/.local/bin/dockerd ]]; then
+#         curl -o .local/bin/slirp4netns --fail -L https://github.com/rootless-containers/slirp4netns/releases/latest/download/slirp4netns-$(uname -m)
+#         chmod +x .local/bin/slirp4netns
+#
+#         curl -fsSL https://get.docker.com/rootless -o ~/.local/bin/get-docker-rootless
+#         chmod +x ~/.local/bin/get-docker-rootless
+#         export DOCKER_BIN=~/.local/bin
+#         export SKIP_IPTABLES=1 
+#         sh ~/.local/bin/get-docker-rootless || ([[ $CAN_SUDO == "true" ]] && sh ~/.local/bin/get-docker-rootless | awk '/cat <<EOF.*/{flag=1;next}/EOF/{flag=0}flag' | sudo bash) && sh ~/.local/bin/get-docker-rootless
+#
+#         mkdir -p ~/.config/systemd/user/docker.service.d
+#         echo "[Service]" > ~/.config/systemd/user/docker.service.d/override.conf
+#         echo 'Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns"' >> ~/.config/systemd/user/docker.service.d/override.conf
+#         [[ $CAN_SUDO == "true" ]] && sudo loginctl enable-linger $(whoami)
+#         export DOCKER_HOST=unix:///$XDG_RUNTIME_DIR/docker.sock
+#         systemctl --user daemon-reload
+#         systemctl --user restart docker
+#         systemctl --user start docker
+#         systemctl --user enable docker
+#
+#         export DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
+#         mkdir -p $DOCKER_CONFIG/cli-plugins
+#         curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
+#         chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
+#         docker network inspect proxy || docker network create proxy
+#         systemctl --user stop docker
+#     else
+#         rm -f ~/.local/bin/dockerd
+#         curl -fsSL https://get.docker.com/rootless -o ~/.local/bin/get-docker-rootless
+#         chmod +x ~/.local/bin/get-docker-rootless
+#
+#         export DOCKER_BIN=~/.local/bin
+#         export SKIP_IPTABLES=1 
+#         sh ~/.local/bin/get-docker-rootless
+#     fi
+# fi
+#
+# if [[ $(yadm config --get-all local.class) == *"dns"* ]]; then
+#     sudo sh -c 'rm /etc/resolv.conf && ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf'
+#     sudo sed -r -i.orig 's/#?DNSStubListener=yes/DNSStubListener=no/g' /etc/resolv.conf
+#     sudo systemctl restart systemd-resolved
+# fi
