Update config

diff --git a/.local/bin/install-all b/.local/bin/install-all
--- a/.local/bin/install-all
+++ b/.local/bin/install-all
@@ -10,7 +10,7 @@ if [[ "$(yadm config --get-all local.class)" != *"work"* ]]; then
     elif command -v pacman > /dev/null; then
         sudo pacman -Syu base-devel procps-ng curl file git
     fi
-    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || (mkdir -p ~/.local/homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C ~/.local/homebrew) && eval "$(brew shellenv)" && brew update --force --quiet && chmod -R go-w "$(brew --prefix)/share/zsh"
+    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && (eval "$(brew shellenv)" && brew update --force --quiet && chmod -R go-w "$(brew --prefix)/share/zsh") || echo "Could not install homebrew"
 fi
 
 if command -v brew > /dev/null; then
@@ -87,7 +87,7 @@ if [[ ! "$(uname -r)" == *"WSL"* ]] && [[ "$(yadm config --get-all local.class)"
     export SKIP_IPTABLES=1 
     sh ~/.local/bin/get-docker-rootless || (sh ~/.local/bin/get-docker-rootless | awk '/cat <<EOF.*/{flag=1;next}/EOF/{flag=0}flag' | sudo bash) && sh ~/.local/bin/get-docker-rootless
 
-    sudo loginctl enable-linger $(whoami) || FAILED_COMMANDS+="Enabling user systemctl failed"
+    sudo loginctl enable-linger $(whoami)
     export DOCKER_HOST=unix:///$XDG_RUNTIME_DIR/docker.sock
     systemctl --user start docker
     systemctl --user enable docker
