Update config

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -165,7 +165,7 @@ yadm checkout .zshrc
 
 echo "All done!"
 
-if [[ $FAILED_COMMANDS != () ]]; then
+if ! [[ ${#FAILED_COMMANDS[@]} -eq 0 ]]; then
     echo "The following commands failed"
 fi
 
